# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER = "cbernazeS"
IP_SERVER = "192.168.56.110"
VM_RAM_MB = "1024"
VM_CPU_NBR = 1

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"

    #Setup VM with k3s server
	config.vm.define SERVER do |server|
		server.vm.hostname = SERVER
		server.vm.network "private_network", ip: IP_SERVER
		server.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--name", SERVER]
			vb.memory = VM_RAM_MB
			vb.cpus = VM_CPU_NBR
		end
		server.vm.provision "shell", inline: <<-SCRIPT
			bash /vagrant/scripts/k3s_server.sh
		SCRIPT
	end
end
